title: Carlos F Buen Abad Najar
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral scholar, University of Chicago.
  <br><br>
  cfbuenabadnajar [at] gmail [dot] com 
  <br><br>
  <a href="https://scholar.google.com/citations?user=PWFEnmQAAAAJ&hl=en&oi=ao/">Publications</a>
  <br><br>
  <a href="https://www.linkedin.com/in/carlos-f-buen-abad-najar-a414651ba/">LinkedIn Profile</a> 

theme: jekyll-theme-minimal
author:
  name: Carlos F Buen Abad Najar
  email: "cfbuenabadn@berkeley.edu"
