title: Carlos F Buen Abad Najar
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD candidate, Computational Biology.
  UC Berkeley.
  <a href="https://www.lareaulab.org">Lareau lab</a> and <a href="https://yoseflab.github.io">Yosef lab</a>
  <br><br>
  cfbuenabadn [at] berkeley [dot] edu 
  <br><br>
  <a href="https://www.linkedin.com/in/carlos-f-buen-abad-najar-a414651ba/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
author:
  name: Carlos F Buen Abad Najar
  email: "cfbuenabadn@berkeley.edu"
